0x03-learn_py/djom_env/djom_project/conversation_app/urls.py
from django.urls import path
from . import views

app_name = 'conversation_app'

urlpatterns = [
    path('new/<int:item_pk>/', views.new_conversation, name='new_conversation'),
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    # path(''),
]

0x03-learn_py/djom_env/djom_project/dashboard_app/urls.py
from django.urls import path
from . import views

app_name = 'dashboard_app'

urlpatterns = [
    path('', views.index, name='index'),
    # path('new/', views.new_item, name='new_item'),
    # path(''),
]

0x03-learn_py/djom_env/djom_project/djom_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from . forms import LoginForm

'''
ADVISORY

do not use the following imports in production.
repeat: do not use the following imports in production
'''
from django.conf import settings
from django.conf.urls.static import static

app_name = 'djom_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='main/login.html', authentication_form=LoginForm),
        name='login'),
    # path(''),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

0x03-learn_py/djom_env/djom_project/djom_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('djom_app.urls')),
    path('items/', include('item_app.urls')),
    path('dashboard/', include('dashboard_app.urls')),
    path('conversation/', include('conversation_app.urls')),
     # path('',),
]

0x03-learn_py/djom_env/djom_project/item_app/urls.py
from django.urls import path
from . import views

app_name = 'item_app'

urlpatterns = [
    path('<int:pk>', views.detail, name='detail'),
    path('new/', views.new_item, name='new_item'),
    path('<int:pk>/delete', views.delete_item, name='delete_item'),
    path('<int:pk>/edit', views.edit_item, name='edit_item'),
    path('', views.items, name='items'),
    # path(''),
]

0x03-learn_py/djom_env/djom_project/djom_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'btesfaye',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'tdibaba@mfano.co.et',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': '************',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': '************',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'btesfaye',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': '************',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

0x03-learn_py/djom_env/djom_project/djom_app/views.py
from django.shortcuts import render, redirect
from item_app.models import Category, Item
from .forms import SignUpForm

def index(req):
    items = Item.objects.filter(is_sold=False)[0:20]
    categories = Category.objects.all()
    return render(request=req, template_name='main/index.html', context={
        'items': items,
        "categories": categories,
    })

def contact(req):
    return render(request=req, template_name='main/contact.html', context={})

def signup(req):
    if req.method == 'POST':
        form = SignUpForm(req.POST)

        if form.is_valid():
            form.save()
            return redirect('/login/')
    else: 
        form = SignUpForm()
    return render(request=req, template_name='main/signup.html', context={
        'form': form
    })

0x03-learn_py/djom_env/djom_project/djom_app/templates/main/base.html
<!DOCTYPE html>
<html lang="en-GB">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://cdn.tailwindcss.com"></script>
        <title>{% block title %}{% endblock title %} | የኤፍ Njakai የገበያ ቦታ</title>
    </head>
    <body>
        <nav class="py-6
            px-6
            flex
            justify-between
            items-center
            border-b
            border-gray-200"
        >
            <a href="/" class="text-xl font-semibold">የኤፍ Njakai የገበያ ቦታ</a>
            <div class="space-x-6">
                <a href="{% url 'item_app:new_item'%}" class="text-lg font-semibold hover:text-gray-500">
                    አዲስ ንጥል | Mapya
                </a>
                <a href="{% url 'item_app:items'%}" class="text-lg font-semibold hover:text-gray-500">
                    ተመልከት | Angalia
                </a>
                {% if request.user.is_authenticated %}
                    <a  href="{% url 'conversation_app:inbox' %}" class="px-6
                        py-3
                        bg-gray-500
                        text-white
                        rounded-xl
                        text-lg
                        font-semibold
                        hover:text-gray-700"
                    >
                        ዲኤም  | Ujumbe
                    </a>
                    <a href="{% url 'dashboard_app:index' %}" class="px-6
                        py-3
                        bg-teal-500
                        text-white
                        rounded-xl
                        text-lg
                        font-semibold
                        hover:text-teal-700"
                    >
                        ዳሽቦርድ | Dashibodi
                    </a>
                {% else %}
                    <a href="{% url 'djom_app:login' %}" class="px-6
                        py-3
                        bg-gray-500
                        text-white
                        rounded-xl
                        text-lg
                        font-semibold
                        hover:text-gray-700"
                    >
                        ግባ | Log in
                    </a>
                    <a href="{% url 'djom_app:signup'%}" class="px-6
                        py-3
                        bg-teal-500
                        text-white
                        rounded-xl
                        text-lg
                        font-semibold
                        hover:text-teal-700"
                    >
                        ተመዝገቢ | Sajili
                    </a>
                {% endif %}
            </div>
        </nav>
        <div >
            {% block content %}{% endblock content %}
        </div>
        <footer class="py-6
            px-6
            flex
            justify-between
            bg-gray-800"
        >
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">
                    About
                </h3>
                <p class="text-lg text-gray-500">FN's Shop</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">
                    Menu
                </h3>
                <ul class="space-y-2">
                    <li>
                        <a href="#" class="text-lg text-teal-500 hover: text-teal-700">
                            About
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'djom_app:contact' %}" class="text-lg text-teal-500 hover: text-teal-700">
                            Contact
                        </a>
                    </li>
                    <li>
                        <a href="#" class="text-lg text-teal-500 hover: text-teal-700">
                            Privacy policy
                        </a>
                    </li>
                    <li>
                        <a href="#" class="text-lg text-teal-500 hover: text-teal-700">
                            Terms of use
                        </a>
                    </li>
                </ul>
            </div>
        </footer>
    </body>
</html>

0x03-learn_py/djom_env/djom_project/djom_app/templates/main/contact.html
{% extends 'main/base.html' %}
{% block title %}Contact{% endblock title %}

{% block content %}
<div class="px-6 py-6">
    <h1>Contact</h1>
</div>
{% endblock content %}

0x03-learn_py/djom_env/djom_project/djom_app/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}Karibu{% endblock title %}

{% block content %}
{% comment %} <div class="px-6 py-6"> {% endcomment %}
<div>
    {% comment %} <h1>የኤፍ Njakai የገበያ ቦታ</h1> {% endcomment %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>
    
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item_app:detail' item.id%}">
                        <div>
                            <img src="{{item.image.url}}" class="rounded-t-xl"/>
                        </div>
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{item.name}}</h2>
                            <p class="text-gray-500">KES  {{item.price|floatformat:"2g"}}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
        <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
            <h2 class="mb-12 text-2xl text-center">Categories</h2>
            <div class="grid grid-cols-3 gap-3">
                {% for category in categories %}
                    <div>
                        <a href="#">
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{category.name}}</h2>
                                <p class="text-gray-500">{{category.items.count}} item(s)</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}




{% comment %} <!DOCTYPE html>
<html lang="en-GB">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://cdn.tailwindcss.com"></script>
        <title>የኤፍ Njakai የገበያ ቦታ</title>
    </head>
    <body>
        <div class="px-6 py-6">
            <h1>Hello, world!</h1>
        </div>
     <body>
</html> {% endcomment %}

0x03-learn_py/djom_env/djom_project/djom_app/templates/main/login.html
{% extends 'main/base.html' %}

{% block title %}Log in{% endblock title %}

{% block content %}
<div class="w-1/3 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>
    <form action="." method="post">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Jina</label><br>
            {{form.username}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{form.password}}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}

                {{form.non_field_errors}}
            </div>
        {% endif %}

        <button class="px-8
            py-4
            text-lg
            bg-teal-500
            hover:bg-teal-700
            rounded-xl
            text-white"
        >
            Log in
        </button>
    </form>
</div>
{% endblock %}

0x03-learn_py/djom_env/djom_project/djom_app/templates/main/signup.html
{% extends 'main/base.html' %}

{% block title %}Sajili{% endblock title %}

{% block content %}
<div class="w-1/3 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">መመዝገብ | Sajili</h1>
    <form action="." method="post">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">ስም | Jina</label><br>
            {{form.username}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">ኢሜይል | Baruapepe</label><br>
            {{form.email}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">የይለፍ ቃል | Password</label><br>
            {{form.password1}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2"> የይለፍ ቃል እንደገና | Rudia password</label><br>
            {{form.password2}}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}

                {{form.non_field_errors}}
            </div>
        {% endif %}

        <button class="px-8
            py-4
            text-lg
            bg-teal-500
            hover:bg-teal-700
            rounded-xl
            text-white"
        >
        መመዝገብ | Sajili
        </button>
    </form>
</div>
{% endblock %}