0x03-learn_py/djom_env/djom_project/conversation_app/urls.py
from django.urls import path
from . import views

app_name = 'conversation_app'

urlpatterns = [
    path('new/<int:item_pk>/', views.new_conversation, name='new_conversation'),
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    # path(''),
]

0x03-learn_py/djom_env/djom_project/djom_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from . forms import LoginForm

'''
ADVISORY

do not use the following imports in production.
repeat: do not use the following imports in production
'''
from django.conf import settings
from django.conf.urls.static import static

app_name = 'djom_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='main/login.html', authentication_form=LoginForm),
        name='login'),
    # path(''),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

0x03-learn_py/djom_env/djom_project/djom_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('djom_app.urls')),
    path('items/', include('item_app.urls')),
    path('dashboard/', include('dashboard_app.urls')),
    path('conversation/', include('conversation_app.urls')),
     # path('',),
]

0x03-learn_py/djom_env/djom_project/item_app/urls.py
from django.urls import path
from . import views

app_name = 'item_app'

urlpatterns = [
    path('<int:pk>', views.detail, name='detail'),
    path('new/', views.new_item, name='new_item'),
    path('<int:pk>/delete', views.delete_item, name='delete_item'),
    path('<int:pk>/edit', views.edit_item, name='edit_item'),
    path('', views.items, name='items'),
    # path(''),
]

0x03-learn_py/djom_env/djom_project/item_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'Categories'
        verbose_name = 'Category'
        ordering = ('name',)
    
    def __str__(self) -> str:
        return f'{self.name}'


class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', null=True, blank=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = 'Items'
        verbose_name = 'Item'
        ordering = ('name',)

    def __str__(self) -> str:
        return f'{self.name}'

0x03-learn_py/djom_env/djom_project/item_app/forms.py
from django import forms
from . models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image',)

        #different way of applying styles
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES,
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES,
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES,
            }),
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold',)

        #different way of applying styles
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES,
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES,
            }),
        }

0x03-learn_py/djom_env/djom_project/item_app/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from .models import Category, Item
from . forms import NewItemForm, EditItemForm

def items(req):
    query = req.GET.get('query', '')
    category_id = req.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    if category_id:
        items = items.filter(category_id=category_id)

    return render(request=req, template_name='items/items.html', context={
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
    })

def detail(req, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request=req, template_name='items/detail.html', context={
        'item': item,
        'related_items': related_items,
    })

@login_required
def new_item(req):
    if req.method == 'POST':
        form = NewItemForm(req.POST, req.FILES)
        if form.is_valid():
            item  = form.save(commit=False)
            item.created_by = req.user
            item.save()

            return redirect('item_app:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request=req, template_name='items/itemForm.html', context={
        'form': form,
        'title': 'Ongeza',
    })

@login_required
def delete_item(req, pk):
    try:
        item = get_object_or_404(Item, pk=pk, created_by=req.user)
    except Exception as e:
        print(f'deleteItemError: {e}')
        return
    else:
        item.delete()
    finally:
        redirect('dashboard_app:index')

@login_required
def edit_item(req, pk):
    item = get_object_or_404(Item, pk=pk, created_by=req.user)
    if req.method == 'POST':
        form = EditItemForm(req.POST, req.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('item_app:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request=req, template_name='items/itemForm.html', context={
        'form': form,
        'title': 'Hariri',
    })

0x03-learn_py/djom_env/djom_project/item_app/templates/items/detail.html
{% extends 'main/base.html' %}

{% block title %}{{item.name}}{% endblock title %}

{% block content %}
<div class="grid grid-cols-5 gap-6 mb-3 ml-3">
    <div class="col-span-3">
        <img src="{{item.image.url}}" class="rounded-xl"/>
    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        <p class="text-gray-500">
            <strong>KES    </strong>
            {{item.price|floatformat:"2g"}}
        </p><br>
        <p class="text-gray-500">
            <strong>ሻጭ | Muuzaji    </strong>
            {{item.created_by.username}}
        </p><br>
        {% if item.description %}
        <p class="text-gray-700">
            <strong class="text-gray-500">መግለጫ | Maelezo</strong><br>
            {{item.description}}
        </p><br/>
        {% endif %}
        {% if request.user == item.created_by %}
        <div class="mt-6 p-6 bg-white rounded-xl">
            <a href="{% url 'item_app:edit_item' item.id %}"
                class="inline-block
                mt-6
                px-6
                py-3
                text-lg
                font-semibold
                bg-teal-500
                text-white
                rounded-xl"
            >
                ሰርዝመለወጥ | Hariri
            </a>
            <a href="{% url 'item_app:delete_item' item.id %}"
                class="inline-block
                mt-6
                px-6
                py-3
                text-lg
                font-semibold
                bg-red-500
                text-white
                rounded-xl"
            >
                ሰርዝ | Futa
            </a>
        </div>
        {% else %}
        <a href="{% url 'conversation_app:new_conversation' item.id %}"
            class="inline-block
            mt-6
            px-6
            py-3
            text-lg
            font-semibold
            bg-teal-500
            text-white
            rounded-xl
            hover:bg-teal-700"
        >
            የእውቂያ ሻጭ | Wasiliana
        </a>
        {% endif %}
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl col-span-5">
        <h2 class="mb-12 text-2xl text-center">Yanayohusiana</h2>
    
        <div class="grid grid-cols-3 gap-3">
            {% for item in related_items %}
                <div>
                    <a href="{% url 'item_app:detail' item.id%}">
                        <div>
                            <img src="{{item.image.url}}" class="rounded-t-xl"/>
                        </div>
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{item.name}}</h2>
                            <p class="text-gray-500">KES  {{item.price}}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

0x03-learn_py/djom_env/djom_project/item_app/templates/items/itemForm.html
{% extends 'main/base.html' %}

{% block title %}{{title}}{% endblock title %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
<h1 class="mb-6 text-3xl ">{{title}}</h1>
<form method='post' action='.' enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{form.as_p}}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{field.errors}}
            {% endfor %}

            {{form.non_field_errors}}
        </div>
    {% endif %}

    <button class=" mt-6 px-8
        py-4
        text-lg
        bg-teal-500
        hover:bg-teal-700
        rounded-xl
        text-white"
    >
        Unda
    </button>
</form>
</div>
{% endblock %}

0x03-learn_py/djom_env/djom_project/item_app/templates/items/items.html
{% extends 'main/base.html' %}

{% block title %}እቃዎች | Bidhaa{% endblock title %}

{% block content %}
<div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
    <div class="col-span-1">
        <form method="get" action="{% url 'item_app:items'%}">
            <input type="text"
                name="query"
                placeholder="ፍለጋ | Tafuta"
                value="{{query}}"
                class="w-full px-6 py-4 border rounded-xl"
            >
            <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">
                ፍለጋ | Tafuta
            </button>
        </form>
        <hr class="my-6">
        <p class="font-semibold"> Categories</p>
        <ul>
            {% for category in categories %}
            <li class="px-2 py-2 rounded-xl
                {% if category.id == category_id %}bg-gray-200{% endif %}
            ">
                <a href="{% url 'item_app:items' %}?query={{query}}&category={{category.id}}">
                    {{category.name}}
                </a>
            </li>
            {% endfor %}
        </ul>
        <hr class="my-6">
        <p class="font-semibold"> Clear filters</p>
        <ul>
            <li>
                <a href="{%url 'item_app:items'%}"
                class="inline-block mt-2 py-4 px-8 text-lg bg-yellow-500 text-white rounded-xl"
                >
                    Clear
                </a>
            </li>
        </ul>
    </div>
    <div class="col-span-3">
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item_app:detail' item.id%}">
                        <div>
                            <img src="{{item.image.url}}" class="rounded-t-xl"/>
                        </div>
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{item.name}}</h2>
                            <p class="text-gray-500">KES  {{item.price|floatformat:"2g"}}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}